export const NOTIFICATIONS_LIST_REQUEST = 'NOTIFICATIONS_LIST_REQUEST';
export const NOTIFICATIONS_LIST_SUCCESS = 'NOTIFICATIONS_LIST_SUCCESS';
export const NOTIFICATIONS_LIST_FAIL    = 'NOTIFICATIONS_LIST_FAIL';

export const NOTIFICATION_RECEIVED = 'NOTIFICATION_RECEIVED';

export const NOTIFICATIONS_MARK_READ = 'NOTIFICATIONS_MARK_READ';
