
# stage 1 - build the application
FROM node:24 AS builder

# Set workdir to /app
WORKDIR /app/common

# Copy both common and users-service into build context
COPY ../common/package*.json ./
COPY ../common/src ./src

RUN npm install

WORKDIR /app/users-service

COPY users-service/package*.json ./
COPY users-service/src ./src

RUN npm install

# stage 2 - create the production image
FROM node:24-alpine AS production

WORKDIR /app/common

COPY --from=builder /app/common ./

WORKDIR /app/users-service

COPY --from=builder /app/users-service ./

# change ownership to the non-root user
RUN chown -R node:node /app

USER node
CMD ["node", "src/server.js"]
ENV PORT=3000
EXPOSE 3000